format: BEngine.Package
version: 2
id: com.bengine.rendering
packageVersion: 1.0.0
displayName: Rendering
description: Runtime rendering, lighting, skybox and UIElements presentation.
enabledByDefault: true
required: true
runtime:
  assembly: BEngine
  rootNamespace: BEngine.Rendering
  dependencies:
  - packageId: com.bengine.core
    target: runtime
  - packageId: com.bengine.ui-elements
    target: runtime
  - packageId: com.bengine.terrain
    target: runtime
    optional: true
editor:
  assembly: BEngine.Editor
  rootNamespace: BEngine.Rendering.Editor
  dependencies:
  - packageId: com.bengine.rendering
    target: runtime
  - packageId: com.bengine.core
    target: editor
  - packageId: com.bengine.ui-elements
    target: editor
