format: BEngine.Project
version: 1
engineVersion: 0.1.0
name: Example
startupScene: Assets/Scenes/Main.scene.yaml
assetsDirectory: Assets
scriptsDirectory: Assets/Scripts
editorScriptsDirectory: Assets/Editor
fixedDeltaTime: 0.02
window:
  title: Example
  width: 1280
  height: 720
  vSync: true
