<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BEngine.Player</RootNamespace>
    <AssemblyName>BEngine.Player</AssemblyName>
    <ApplicationIcon>../BEngine.Icons/BEngine.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BEngine/BEngine.csproj" />
    <PackageReference Include="Silk.NET.Windowing" />
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.OpenGL" />
  </ItemGroup>
</Project>
