<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>BEngine.ExampleTests.EditorProgress</RootNamespace>
    <AssemblyName>BEngine.ExampleTests.EditorProgress</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Core/BEngine.Editor/BEngine.Editor.csproj" />
  </ItemGroup>
</Project>
