format: BEngine.ProjectSettings
version: 3
locale: zh-CN
companyName: BEngine
productName: BEngine 2D Showcase
defaultScreenWidth: 1280
defaultScreenHeight: 720
fullScreen: false
graphicsBackend: Vulkan
scriptingDefineSymbols: []
tags:
- Untagged
- Respawn
- Finish
- EditorOnly
- MainCamera
- Player
- GameController
sortingLayers:
- value: 1
  name: Background
  builtIn: true
  isUi: false
  builtInId: Default
- value: 2
  name: Gameplay
  builtIn: true
  isUi: false
  builtInId: TransparentFX
- value: 3
  name: Foreground
  builtIn: true
  isUi: false
  builtInId: IgnoreRaycast
- value: 4
  name: Inset Only
  builtIn: true
  isUi: false
  builtInId: Water
- value: 5
  name: UI
  builtIn: true
  isUi: true
  builtInId: UI
