<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BEngine.PropertyAttributes</RootNamespace>
    <AssemblyName>BEngine.PropertyAttributes</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Core/BEngine/BEngine.csproj" />
  </ItemGroup>
</Project>
