<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BEngine.Physics2D</RootNamespace>
    <AssemblyName>BEngine.Physics2D</AssemblyName>
    <NoWarn>$(NoWarn);CA2255</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Core/BEngine/BEngine.csproj" />
  </ItemGroup>
</Project>
