<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BEngine.ExampleTests.ProjectFolderTree</RootNamespace>
    <AssemblyName>BEngine.ExampleTests.ProjectFolderTree</AssemblyName>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Core/BEngine/BEngine.csproj" />
    <ProjectReference Include="../../../src/Packages/UIElements/BEngine.UIElements/BEngine.UIElements.csproj" />
  </ItemGroup>
</Project>
