namespace BEngine.Editor;

public sealed partial class GUISkin
{
    public GUIStyle miniBoldLabel { get; set; } = Style("miniBoldLabel");
    public GUIStyle centeredGreyMiniLabel { get; set; } = new("centeredGreyMiniLabel")
    {
        alignment = TextAnchor.MiddleCenter
    };
    public GUIStyle wordWrappedMiniLabel { get; set; } = new("wordWrappedMiniLabel") { wordWrap = true };
    public GUIStyle wordWrappedLabel { get; set; } = new("wordWrappedLabel") { wordWrap = true };
    public GUIStyle whiteLabel { get; set; } = Style("whiteLabel");
    public GUIStyle whiteMiniLabel { get; set; } = Style("whiteMiniLabel");
    public GUIStyle whiteLargeLabel { get; set; } = Style("whiteLargeLabel");
    public GUIStyle whiteBoldLabel { get; set; } = Style("whiteBoldLabel");
    public GUIStyle radioButton { get; set; } = Style("radioButton");
    public GUIStyle miniButtonLeft { get; set; } = Style("miniButtonLeft");
    public GUIStyle miniButtonMid { get; set; } = Style("miniButtonMid");
    public GUIStyle miniButtonRight { get; set; } = Style("miniButtonRight");
    public GUIStyle miniPullDown { get; set; } = Style("miniPullDown");
    public GUIStyle boldTextField { get; set; } = Style("boldTextField");
    public GUIStyle miniTextField { get; set; } = Style("miniTextField");
    public GUIStyle objectField { get; set; } = Style("objectField");
    public GUIStyle objectFieldButton { get; set; } = Style("objectFieldButton");
    public GUIStyle objectFieldThumb { get; set; } = Style("objectFieldThumb");
    public GUIStyle objectFieldMiniThumb { get; set; } = Style("objectFieldMiniThumb");
    public GUIStyle layerMaskField { get; set; } = Style("layerMaskField");
    public GUIStyle toggleMixed { get; set; } = Style("toggleMixed");
    public GUIStyle titlebarFoldout { get; set; } = Style("titlebarFoldout");
    public GUIStyle foldoutPreDrop { get; set; } = Style("foldoutPreDrop");
    public GUIStyle foldoutHeader { get; set; } = Style("foldoutHeader");
    public GUIStyle foldoutHeaderIcon { get; set; } = Style("foldoutHeaderIcon");
    public GUIStyle optionsButtonStyle { get; set; } = IconButton("optionsButtonStyle");
    public GUIStyle toggleGroup { get; set; } = Style("toggleGroup");
    public GUIStyle textFieldDropDown { get; set; } = Style("textFieldDropDown");
    public GUIStyle textFieldDropDownText { get; set; } = Style("textFieldDropDownText");
    public GUIStyle overrideMargin { get; set; } = Style("overrideMargin");
    public GUIStyle contentToolbar { get; set; } = Style("contentToolbar");
    public GUIStyle toolbarToggle { get; set; } = Style("toolbarToggle");
    public GUIStyle toolbarButtonLeft { get; set; } = Style("toolbarButtonLeft");
    public GUIStyle toolbarButtonRight { get; set; } = Style("toolbarButtonRight");
    public GUIStyle toolbarPopup { get; set; } = Style("toolbarPopup");
    public GUIStyle toolbarPopupLeft { get; set; } = Style("toolbarPopupLeft");
    public GUIStyle toolbarPopupRight { get; set; } = Style("toolbarPopupRight");
    public GUIStyle toolbarDropDownLeft { get; set; } = Style("toolbarDropDownLeft");
    public GUIStyle toolbarDropDown { get; set; } = Style("toolbarDropDown");
    public GUIStyle toolbarDropDownRight { get; set; } = Style("toolbarDropDownRight");
    public GUIStyle toolbarDropDownToggle { get; set; } = Style("toolbarDropDownToggle");
    public GUIStyle toolbarDropDownToggleButton { get; set; } = Style("toolbarDropDownToggleButton");
    public GUIStyle toolbarDropDownToggleRight { get; set; } = Style("toolbarDropDownToggleRight");
    public GUIStyle toolbarCreateAddNewDropDown { get; set; } = Style("toolbarCreateAddNewDropDown");
    public GUIStyle toolbarTextField { get; set; } = Style("toolbarTextField");
    public GUIStyle toolbarLabel { get; set; } = Style("toolbarLabel");
    public GUIStyle inspectorHorizontalDefaultMargins { get; set; } = Style("inspectorHorizontalDefaultMargins");
    public GUIStyle inspectorFullWidthMargins { get; set; } = Style("inspectorFullWidthMargins");
    public GUIStyle defaultContentMargins { get; set; } = Style("defaultContentMargins");
    public GUIStyle frameBox { get; set; } = Style("frameBox");
    public GUIStyle toolbarSearchFieldPopup { get; set; } = Style("toolbarSearchFieldPopup");
    public GUIStyle toolbarSearchFieldWithJumpSynced { get; set; } = Style("toolbarSearchFieldWithJumpSynced");
    public GUIStyle toolbarSearchFieldWithJumpPopupSynced { get; set; } =
        Style("toolbarSearchFieldWithJumpPopupSynced");
    public GUIStyle toolbarSearchFieldWithJump { get; set; } = Style("toolbarSearchFieldWithJump");
    public GUIStyle toolbarSearchFieldWithJumpPopup { get; set; } = Style("toolbarSearchFieldWithJumpPopup");
    public GUIStyle toolbarSearchFieldJumpButton { get; set; } = IconButton("toolbarSearchFieldJumpButton");
    public GUIStyle toolbarSearchFieldCancelButton { get; set; } = IconButton("toolbarSearchFieldCancelButton");
    public GUIStyle toolbarSearchFieldCancelButtonEmpty { get; set; } =
        IconButton("toolbarSearchFieldCancelButtonEmpty");
    public GUIStyle toolbarSearchFieldCancelButtonWithJump { get; set; } =
        IconButton("toolbarSearchFieldCancelButtonWithJump");
    public GUIStyle toolbarSearchFieldCancelButtonWithJumpEmpty { get; set; } =
        IconButton("toolbarSearchFieldCancelButtonWithJumpEmpty");
    public GUIStyle colorPickerBox { get; set; } = Style("colorPickerBox");
    public GUIStyle viewBackground { get; set; } = Style("viewBackground");
    public GUIStyle inspectorBig { get; set; } = Style("inspectorBig");
    public GUIStyle inspectorTitlebarFlat { get; set; } = Style("inspectorTitlebarFlat");
    public GUIStyle inspectorTitlebarText { get; set; } = Style("inspectorTitlebarText");
    public GUIStyle foldoutSelected { get; set; } = Style("foldoutSelected");
    public GUIStyle iconButton { get; set; } = IconButton("iconButton");
    public GUIStyle tooltip { get; set; } = Style("tooltip");
    public GUIStyle notificationText { get; set; } = Style("notificationText");
    public GUIStyle notificationBackground { get; set; } = Style("notificationBackground");
    public GUIStyle assetLabel { get; set; } = Style("assetLabel");
    public GUIStyle assetLabelPartial { get; set; } = Style("assetLabelPartial");
    public GUIStyle assetLabelIcon { get; set; } = Style("assetLabelIcon");
    public GUIStyle searchField { get; set; } = Style("searchField");
    public GUIStyle searchFieldCancelButton { get; set; } = IconButton("searchFieldCancelButton");
    public GUIStyle searchFieldCancelButtonEmpty { get; set; } = IconButton("searchFieldCancelButtonEmpty");
    public GUIStyle selectionRect { get; set; } = Style("selectionRect");
    public GUIStyle toolbarSlider { get; set; } = Style("toolbarSlider");
    public GUIStyle minMaxHorizontalSliderThumb { get; set; } = Style("minMaxHorizontalSliderThumb");
    public GUIStyle dropDownList { get; set; } = Style("dropDownList");
    public GUIStyle dropDownToggleButton { get; set; } = Style("dropDownToggleButton");
    public GUIStyle minMaxStateDropdown { get; set; } = Style("minMaxStateDropdown");
    public GUIStyle progressBarBack { get; set; } = Style("progressBarBack");
    public GUIStyle progressBarBar { get; set; } = Style("progressBarBar");
    public GUIStyle progressBarText { get; set; } = Style("progressBarText");
    public GUIStyle scrollViewAlt { get; set; } = Style("scrollViewAlt");

    private IEnumerable<(string Name, GUIStyle Style)> EnumerateExtendedEditorStyles()
    {
        yield return ("miniBoldLabel", miniBoldLabel);
        yield return ("centeredGreyMiniLabel", centeredGreyMiniLabel);
        yield return ("wordWrappedMiniLabel", wordWrappedMiniLabel);
        yield return ("wordWrappedLabel", wordWrappedLabel);
        yield return ("whiteLabel", whiteLabel);
        yield return ("whiteMiniLabel", whiteMiniLabel);
        yield return ("whiteLargeLabel", whiteLargeLabel);
        yield return ("whiteBoldLabel", whiteBoldLabel);
        yield return ("radioButton", radioButton);
        yield return ("miniButtonLeft", miniButtonLeft);
        yield return ("miniButtonMid", miniButtonMid);
        yield return ("miniButtonRight", miniButtonRight);
        yield return ("miniPullDown", miniPullDown);
        yield return ("boldTextField", boldTextField);
        yield return ("miniTextField", miniTextField);
        yield return ("objectField", objectField);
        yield return ("objectFieldButton", objectFieldButton);
        yield return ("objectFieldThumb", objectFieldThumb);
        yield return ("objectFieldMiniThumb", objectFieldMiniThumb);
        yield return ("layerMaskField", layerMaskField);
        yield return ("toggleMixed", toggleMixed);
        yield return ("titlebarFoldout", titlebarFoldout);
        yield return ("foldoutPreDrop", foldoutPreDrop);
        yield return ("foldoutHeader", foldoutHeader);
        yield return ("foldoutHeaderIcon", foldoutHeaderIcon);
        yield return ("optionsButtonStyle", optionsButtonStyle);
        yield return ("toggleGroup", toggleGroup);
        yield return ("textFieldDropDown", textFieldDropDown);
        yield return ("textFieldDropDownText", textFieldDropDownText);
        yield return ("overrideMargin", overrideMargin);
        yield return ("contentToolbar", contentToolbar);
        yield return ("toolbarToggle", toolbarToggle);
        yield return ("toolbarButtonLeft", toolbarButtonLeft);
        yield return ("toolbarButtonRight", toolbarButtonRight);
        yield return ("toolbarPopup", toolbarPopup);
        yield return ("toolbarPopupLeft", toolbarPopupLeft);
        yield return ("toolbarPopupRight", toolbarPopupRight);
        yield return ("toolbarDropDownLeft", toolbarDropDownLeft);
        yield return ("toolbarDropDown", toolbarDropDown);
        yield return ("toolbarDropDownRight", toolbarDropDownRight);
        yield return ("toolbarDropDownToggle", toolbarDropDownToggle);
        yield return ("toolbarDropDownToggleButton", toolbarDropDownToggleButton);
        yield return ("toolbarDropDownToggleRight", toolbarDropDownToggleRight);
        yield return ("toolbarCreateAddNewDropDown", toolbarCreateAddNewDropDown);
        yield return ("toolbarTextField", toolbarTextField);
        yield return ("toolbarLabel", toolbarLabel);
        yield return ("inspectorHorizontalDefaultMargins", inspectorHorizontalDefaultMargins);
        yield return ("inspectorFullWidthMargins", inspectorFullWidthMargins);
        yield return ("defaultContentMargins", defaultContentMargins);
        yield return ("frameBox", frameBox);
        yield return ("toolbarSearchFieldPopup", toolbarSearchFieldPopup);
        yield return ("toolbarSearchFieldWithJumpSynced", toolbarSearchFieldWithJumpSynced);
        yield return ("toolbarSearchFieldWithJumpPopupSynced", toolbarSearchFieldWithJumpPopupSynced);
        yield return ("toolbarSearchFieldWithJump", toolbarSearchFieldWithJump);
        yield return ("toolbarSearchFieldWithJumpPopup", toolbarSearchFieldWithJumpPopup);
        yield return ("toolbarSearchFieldJumpButton", toolbarSearchFieldJumpButton);
        yield return ("toolbarSearchFieldCancelButton", toolbarSearchFieldCancelButton);
        yield return ("toolbarSearchFieldCancelButtonEmpty", toolbarSearchFieldCancelButtonEmpty);
        yield return ("toolbarSearchFieldCancelButtonWithJump", toolbarSearchFieldCancelButtonWithJump);
        yield return ("toolbarSearchFieldCancelButtonWithJumpEmpty", toolbarSearchFieldCancelButtonWithJumpEmpty);
        yield return ("colorPickerBox", colorPickerBox);
        yield return ("viewBackground", viewBackground);
        yield return ("inspectorBig", inspectorBig);
        yield return ("inspectorTitlebarFlat", inspectorTitlebarFlat);
        yield return ("inspectorTitlebarText", inspectorTitlebarText);
        yield return ("foldoutSelected", foldoutSelected);
        yield return ("iconButton", iconButton);
        yield return ("tooltip", tooltip);
        yield return ("notificationText", notificationText);
        yield return ("notificationBackground", notificationBackground);
        yield return ("assetLabel", assetLabel);
        yield return ("assetLabelPartial", assetLabelPartial);
        yield return ("assetLabelIcon", assetLabelIcon);
        yield return ("searchField", searchField);
        yield return ("searchFieldCancelButton", searchFieldCancelButton);
        yield return ("searchFieldCancelButtonEmpty", searchFieldCancelButtonEmpty);
        yield return ("selectionRect", selectionRect);
        yield return ("toolbarSlider", toolbarSlider);
        yield return ("minMaxHorizontalSliderThumb", minMaxHorizontalSliderThumb);
        yield return ("dropDownList", dropDownList);
        yield return ("dropDownToggleButton", dropDownToggleButton);
        yield return ("minMaxStateDropdown", minMaxStateDropdown);
        yield return ("progressBarBack", progressBarBack);
        yield return ("progressBarBar", progressBarBar);
        yield return ("progressBarText", progressBarText);
        yield return ("scrollViewAlt", scrollViewAlt);
    }
}
