<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>BEngine.Launcher</RootNamespace>
    <AssemblyName>BEngine.Launcher</AssemblyName>
    <ApplicationIcon>../BEngine.Icons/BEngine.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BEngine/BEngine.csproj" />
    <ProjectReference Include="../BEngine.Editor/BEngine.Editor.csproj" />
  </ItemGroup>
</Project>
