using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("BEngine.Tests")]
[assembly: InternalsVisibleTo("BEngine.UIElements.Editor.Tests")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.GpuImGui")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.GpuDockWindowStates")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.EditorLayoutPersistence")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.ProjectPackageTree")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.TreeViewDragRename")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.ProjectPackageCache")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.ThreadingArchitecture")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.EditorSettingsWindows")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.GameViewResolution")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.ProjectAssetWorkflow")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.PackageExamples")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.EditorProgress")]
[assembly: InternalsVisibleTo("BEngine.ExampleTests.FrameDebugger")]
