<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>BEngine.ExampleTests.PrefabWorkflow</RootNamespace>
    <AssemblyName>BEngine.ExampleTests.PrefabWorkflow</AssemblyName>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Core/BEngine/BEngine.csproj" />
    <ProjectReference Include="../../../src/Core/BEngine.Editor/BEngine.Editor.csproj" />
  </ItemGroup>
</Project>
