<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BEngine</RootNamespace>
    <AssemblyName>BEngine</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Silk.NET.OpenGL" />
    <PackageReference Include="Silk.NET.Windowing" />
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Veldrid" />
    <PackageReference Include="Veldrid.SPIRV" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" Exclude="bin/**/*.cs;obj/**/*.cs" />
  </ItemGroup>
</Project>
