namespace BEngine.Editor;

public sealed partial class GUISkin
{
    public GUIStyle miniBoldLabel { get; set; } = Style(nameof(miniBoldLabel));
    public GUIStyle centeredGreyMiniLabel { get; set; } = new(nameof(centeredGreyMiniLabel))
    {
        alignment = TextAnchor.MiddleCenter
    };
    public GUIStyle wordWrappedMiniLabel { get; set; } = new(nameof(wordWrappedMiniLabel)) { wordWrap = true };
    public GUIStyle wordWrappedLabel { get; set; } = new(nameof(wordWrappedLabel)) { wordWrap = true };
    public GUIStyle whiteLabel { get; set; } = Style(nameof(whiteLabel));
    public GUIStyle whiteMiniLabel { get; set; } = Style(nameof(whiteMiniLabel));
    public GUIStyle whiteLargeLabel { get; set; } = Style(nameof(whiteLargeLabel));
    public GUIStyle whiteBoldLabel { get; set; } = Style(nameof(whiteBoldLabel));
    public GUIStyle radioButton { get; set; } = Style(nameof(radioButton));
    public GUIStyle miniButtonLeft { get; set; } = Style(nameof(miniButtonLeft));
    public GUIStyle miniButtonMid { get; set; } = Style(nameof(miniButtonMid));
    public GUIStyle miniButtonRight { get; set; } = Style(nameof(miniButtonRight));
    public GUIStyle miniPullDown { get; set; } = Style(nameof(miniPullDown));
    public GUIStyle boldTextField { get; set; } = Style(nameof(boldTextField));
    public GUIStyle miniTextField { get; set; } = Style(nameof(miniTextField));
    public GUIStyle objectField { get; set; } = Style(nameof(objectField));
    public GUIStyle objectFieldButton { get; set; } = Style(nameof(objectFieldButton));
    public GUIStyle objectFieldThumb { get; set; } = Style(nameof(objectFieldThumb));
    public GUIStyle objectFieldMiniThumb { get; set; } = Style(nameof(objectFieldMiniThumb));
    public GUIStyle layerMaskField { get; set; } = Style(nameof(layerMaskField));
    public GUIStyle toggleMixed { get; set; } = Style(nameof(toggleMixed));
    public GUIStyle titlebarFoldout { get; set; } = Style(nameof(titlebarFoldout));
    public GUIStyle foldoutPreDrop { get; set; } = Style(nameof(foldoutPreDrop));
    public GUIStyle foldoutHeader { get; set; } = Style(nameof(foldoutHeader));
    public GUIStyle foldoutHeaderIcon { get; set; } = Style(nameof(foldoutHeaderIcon));
    public GUIStyle optionsButtonStyle { get; set; } = IconButton(nameof(optionsButtonStyle));
    public GUIStyle toggleGroup { get; set; } = Style(nameof(toggleGroup));
    public GUIStyle textFieldDropDown { get; set; } = Style(nameof(textFieldDropDown));
    public GUIStyle textFieldDropDownText { get; set; } = Style(nameof(textFieldDropDownText));
    public GUIStyle overrideMargin { get; set; } = Style(nameof(overrideMargin));
    public GUIStyle contentToolbar { get; set; } = Style(nameof(contentToolbar));
    public GUIStyle toolbarToggle { get; set; } = Style(nameof(toolbarToggle));
    public GUIStyle toolbarButtonLeft { get; set; } = Style(nameof(toolbarButtonLeft));
    public GUIStyle toolbarButtonRight { get; set; } = Style(nameof(toolbarButtonRight));
    public GUIStyle toolbarPopup { get; set; } = Style(nameof(toolbarPopup));
    public GUIStyle toolbarPopupLeft { get; set; } = Style(nameof(toolbarPopupLeft));
    public GUIStyle toolbarPopupRight { get; set; } = Style(nameof(toolbarPopupRight));
    public GUIStyle toolbarDropDownLeft { get; set; } = Style(nameof(toolbarDropDownLeft));
    public GUIStyle toolbarDropDown { get; set; } = Style(nameof(toolbarDropDown));
    public GUIStyle toolbarDropDownRight { get; set; } = Style(nameof(toolbarDropDownRight));
    public GUIStyle toolbarDropDownToggle { get; set; } = Style(nameof(toolbarDropDownToggle));
    public GUIStyle toolbarDropDownToggleButton { get; set; } = Style(nameof(toolbarDropDownToggleButton));
    public GUIStyle toolbarDropDownToggleRight { get; set; } = Style(nameof(toolbarDropDownToggleRight));
    public GUIStyle toolbarCreateAddNewDropDown { get; set; } = Style(nameof(toolbarCreateAddNewDropDown));
    public GUIStyle toolbarTextField { get; set; } = Style(nameof(toolbarTextField));
    public GUIStyle toolbarLabel { get; set; } = Style(nameof(toolbarLabel));
    public GUIStyle inspectorHorizontalDefaultMargins { get; set; } = Style(nameof(inspectorHorizontalDefaultMargins));
    public GUIStyle inspectorFullWidthMargins { get; set; } = Style(nameof(inspectorFullWidthMargins));
    public GUIStyle defaultContentMargins { get; set; } = Style(nameof(defaultContentMargins));
    public GUIStyle frameBox { get; set; } = Style(nameof(frameBox));
    public GUIStyle helpBoxLabel { get; set; } = new(nameof(helpBoxLabel)) { wordWrap = true };
    public GUIStyle toolbarSearchFieldPopup { get; set; } = Style(nameof(toolbarSearchFieldPopup));
    public GUIStyle toolbarSearchFieldWithJumpSynced { get; set; } = Style(nameof(toolbarSearchFieldWithJumpSynced));
    public GUIStyle toolbarSearchFieldWithJumpPopupSynced { get; set; } =
        Style(nameof(toolbarSearchFieldWithJumpPopupSynced));
    public GUIStyle toolbarSearchFieldWithJump { get; set; } = Style(nameof(toolbarSearchFieldWithJump));
    public GUIStyle toolbarSearchFieldWithJumpPopup { get; set; } = Style(nameof(toolbarSearchFieldWithJumpPopup));
    public GUIStyle toolbarSearchFieldJumpButton { get; set; } = IconButton(nameof(toolbarSearchFieldJumpButton));
    public GUIStyle toolbarSearchFieldCancelButton { get; set; } = IconButton(nameof(toolbarSearchFieldCancelButton));
    public GUIStyle toolbarSearchFieldCancelButtonEmpty { get; set; } =
        IconButton(nameof(toolbarSearchFieldCancelButtonEmpty));
    public GUIStyle toolbarSearchFieldCancelButtonWithJump { get; set; } =
        IconButton(nameof(toolbarSearchFieldCancelButtonWithJump));
    public GUIStyle toolbarSearchFieldCancelButtonWithJumpEmpty { get; set; } =
        IconButton(nameof(toolbarSearchFieldCancelButtonWithJumpEmpty));
    public GUIStyle colorPickerBox { get; set; } = Style(nameof(colorPickerBox));
    public GUIStyle viewBackground { get; set; } = Style(nameof(viewBackground));
    public GUIStyle inspectorBig { get; set; } = Style(nameof(inspectorBig));
    public GUIStyle inspectorTitlebarFlat { get; set; } = Style(nameof(inspectorTitlebarFlat));
    public GUIStyle inspectorTitlebarText { get; set; } = Style(nameof(inspectorTitlebarText));
    public GUIStyle foldoutSelected { get; set; } = Style(nameof(foldoutSelected));
    public GUIStyle iconButton { get; set; } = IconButton(nameof(iconButton));
    public GUIStyle tooltip { get; set; } = Style(nameof(tooltip));
    public GUIStyle notificationText { get; set; } = Style(nameof(notificationText));
    public GUIStyle notificationBackground { get; set; } = Style(nameof(notificationBackground));
    public GUIStyle assetLabel { get; set; } = Style(nameof(assetLabel));
    public GUIStyle assetLabelPartial { get; set; } = Style(nameof(assetLabelPartial));
    public GUIStyle assetLabelIcon { get; set; } = Style(nameof(assetLabelIcon));
    public GUIStyle searchField { get; set; } = Style(nameof(searchField));
    public GUIStyle searchFieldCancelButton { get; set; } = IconButton(nameof(searchFieldCancelButton));
    public GUIStyle searchFieldCancelButtonEmpty { get; set; } = IconButton(nameof(searchFieldCancelButtonEmpty));
    public GUIStyle selectionRect { get; set; } = Style(nameof(selectionRect));
    public GUIStyle toolbarSlider { get; set; } = Style(nameof(toolbarSlider));
    public GUIStyle minMaxHorizontalSliderThumb { get; set; } = Style(nameof(minMaxHorizontalSliderThumb));
    public GUIStyle dropDownList { get; set; } = Style(nameof(dropDownList));
    public GUIStyle dropDownToggleButton { get; set; } = Style(nameof(dropDownToggleButton));
    public GUIStyle minMaxStateDropdown { get; set; } = Style(nameof(minMaxStateDropdown));
    public GUIStyle progressBarBack { get; set; } = Style(nameof(progressBarBack));
    public GUIStyle progressBarBar { get; set; } = Style(nameof(progressBarBar));
    public GUIStyle progressBarText { get; set; } = Style(nameof(progressBarText));
    public GUIStyle scrollViewAlt { get; set; } = Style(nameof(scrollViewAlt));

    private IEnumerable<(string Name, GUIStyle Style)> EnumerateExtendedEditorStyles()
    {
        yield return (nameof(miniBoldLabel), miniBoldLabel);
        yield return (nameof(centeredGreyMiniLabel), centeredGreyMiniLabel);
        yield return (nameof(wordWrappedMiniLabel), wordWrappedMiniLabel);
        yield return (nameof(wordWrappedLabel), wordWrappedLabel);
        yield return (nameof(whiteLabel), whiteLabel);
        yield return (nameof(whiteMiniLabel), whiteMiniLabel);
        yield return (nameof(whiteLargeLabel), whiteLargeLabel);
        yield return (nameof(whiteBoldLabel), whiteBoldLabel);
        yield return (nameof(radioButton), radioButton);
        yield return (nameof(miniButtonLeft), miniButtonLeft);
        yield return (nameof(miniButtonMid), miniButtonMid);
        yield return (nameof(miniButtonRight), miniButtonRight);
        yield return (nameof(miniPullDown), miniPullDown);
        yield return (nameof(boldTextField), boldTextField);
        yield return (nameof(miniTextField), miniTextField);
        yield return (nameof(objectField), objectField);
        yield return (nameof(objectFieldButton), objectFieldButton);
        yield return (nameof(objectFieldThumb), objectFieldThumb);
        yield return (nameof(objectFieldMiniThumb), objectFieldMiniThumb);
        yield return (nameof(layerMaskField), layerMaskField);
        yield return (nameof(toggleMixed), toggleMixed);
        yield return (nameof(titlebarFoldout), titlebarFoldout);
        yield return (nameof(foldoutPreDrop), foldoutPreDrop);
        yield return (nameof(foldoutHeader), foldoutHeader);
        yield return (nameof(foldoutHeaderIcon), foldoutHeaderIcon);
        yield return (nameof(optionsButtonStyle), optionsButtonStyle);
        yield return (nameof(toggleGroup), toggleGroup);
        yield return (nameof(textFieldDropDown), textFieldDropDown);
        yield return (nameof(textFieldDropDownText), textFieldDropDownText);
        yield return (nameof(overrideMargin), overrideMargin);
        yield return (nameof(contentToolbar), contentToolbar);
        yield return (nameof(toolbarToggle), toolbarToggle);
        yield return (nameof(toolbarButtonLeft), toolbarButtonLeft);
        yield return (nameof(toolbarButtonRight), toolbarButtonRight);
        yield return (nameof(toolbarPopup), toolbarPopup);
        yield return (nameof(toolbarPopupLeft), toolbarPopupLeft);
        yield return (nameof(toolbarPopupRight), toolbarPopupRight);
        yield return (nameof(toolbarDropDownLeft), toolbarDropDownLeft);
        yield return (nameof(toolbarDropDown), toolbarDropDown);
        yield return (nameof(toolbarDropDownRight), toolbarDropDownRight);
        yield return (nameof(toolbarDropDownToggle), toolbarDropDownToggle);
        yield return (nameof(toolbarDropDownToggleButton), toolbarDropDownToggleButton);
        yield return (nameof(toolbarDropDownToggleRight), toolbarDropDownToggleRight);
        yield return (nameof(toolbarCreateAddNewDropDown), toolbarCreateAddNewDropDown);
        yield return (nameof(toolbarTextField), toolbarTextField);
        yield return (nameof(toolbarLabel), toolbarLabel);
        yield return (nameof(inspectorHorizontalDefaultMargins), inspectorHorizontalDefaultMargins);
        yield return (nameof(inspectorFullWidthMargins), inspectorFullWidthMargins);
        yield return (nameof(defaultContentMargins), defaultContentMargins);
        yield return (nameof(frameBox), frameBox);
        yield return (nameof(helpBoxLabel), helpBoxLabel);
        yield return (nameof(toolbarSearchFieldPopup), toolbarSearchFieldPopup);
        yield return (nameof(toolbarSearchFieldWithJumpSynced), toolbarSearchFieldWithJumpSynced);
        yield return (nameof(toolbarSearchFieldWithJumpPopupSynced), toolbarSearchFieldWithJumpPopupSynced);
        yield return (nameof(toolbarSearchFieldWithJump), toolbarSearchFieldWithJump);
        yield return (nameof(toolbarSearchFieldWithJumpPopup), toolbarSearchFieldWithJumpPopup);
        yield return (nameof(toolbarSearchFieldJumpButton), toolbarSearchFieldJumpButton);
        yield return (nameof(toolbarSearchFieldCancelButton), toolbarSearchFieldCancelButton);
        yield return (nameof(toolbarSearchFieldCancelButtonEmpty), toolbarSearchFieldCancelButtonEmpty);
        yield return (nameof(toolbarSearchFieldCancelButtonWithJump), toolbarSearchFieldCancelButtonWithJump);
        yield return (nameof(toolbarSearchFieldCancelButtonWithJumpEmpty), toolbarSearchFieldCancelButtonWithJumpEmpty);
        yield return (nameof(colorPickerBox), colorPickerBox);
        yield return (nameof(viewBackground), viewBackground);
        yield return (nameof(inspectorBig), inspectorBig);
        yield return (nameof(inspectorTitlebarFlat), inspectorTitlebarFlat);
        yield return (nameof(inspectorTitlebarText), inspectorTitlebarText);
        yield return (nameof(foldoutSelected), foldoutSelected);
        yield return (nameof(iconButton), iconButton);
        yield return (nameof(tooltip), tooltip);
        yield return (nameof(notificationText), notificationText);
        yield return (nameof(notificationBackground), notificationBackground);
        yield return (nameof(assetLabel), assetLabel);
        yield return (nameof(assetLabelPartial), assetLabelPartial);
        yield return (nameof(assetLabelIcon), assetLabelIcon);
        yield return (nameof(searchField), searchField);
        yield return (nameof(searchFieldCancelButton), searchFieldCancelButton);
        yield return (nameof(searchFieldCancelButtonEmpty), searchFieldCancelButtonEmpty);
        yield return (nameof(selectionRect), selectionRect);
        yield return (nameof(toolbarSlider), toolbarSlider);
        yield return (nameof(minMaxHorizontalSliderThumb), minMaxHorizontalSliderThumb);
        yield return (nameof(dropDownList), dropDownList);
        yield return (nameof(dropDownToggleButton), dropDownToggleButton);
        yield return (nameof(minMaxStateDropdown), minMaxStateDropdown);
        yield return (nameof(progressBarBack), progressBarBack);
        yield return (nameof(progressBarBar), progressBarBar);
        yield return (nameof(progressBarText), progressBarText);
        yield return (nameof(scrollViewAlt), scrollViewAlt);
    }
}
